/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as ResultRouteImport } from './routes/result'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as BeginRouteImport } from './routes/begin'
import { Route as AnalyzingRouteImport } from './routes/analyzing'
import { Route as IndexRouteImport } from './routes/index'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultRoute = ResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const BeginRoute = BeginRouteImport.update({
  id: '/begin',
  path: '/begin',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzingRoute = AnalyzingRouteImport.update({
  id: '/analyzing',
  path: '/analyzing',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analyzing': typeof AnalyzingRoute
  '/begin': typeof BeginRoute
  '/guide': typeof GuideRoute
  '/result': typeof ResultRoute
  '/upload': typeof UploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analyzing': typeof AnalyzingRoute
  '/begin': typeof BeginRoute
  '/guide': typeof GuideRoute
  '/result': typeof ResultRoute
  '/upload': typeof UploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analyzing': typeof AnalyzingRoute
  '/begin': typeof BeginRoute
  '/guide': typeof GuideRoute
  '/result': typeof ResultRoute
  '/upload': typeof UploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/analyzing' | '/begin' | '/guide' | '/result' | '/upload'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/analyzing' | '/begin' | '/guide' | '/result' | '/upload'
  id:
    | '__root__'
    | '/'
    | '/analyzing'
    | '/begin'
    | '/guide'
    | '/result'
    | '/upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyzingRoute: typeof AnalyzingRoute
  BeginRoute: typeof BeginRoute
  GuideRoute: typeof GuideRoute
  ResultRoute: typeof ResultRoute
  UploadRoute: typeof UploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result': {
      id: '/result'
      path: '/result'
      fullPath: '/result'
      preLoaderRoute: typeof ResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/begin': {
      id: '/begin'
      path: '/begin'
      fullPath: '/begin'
      preLoaderRoute: typeof BeginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyzing': {
      id: '/analyzing'
      path: '/analyzing'
      fullPath: '/analyzing'
      preLoaderRoute: typeof AnalyzingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyzingRoute: AnalyzingRoute,
  BeginRoute: BeginRoute,
  GuideRoute: GuideRoute,
  ResultRoute: ResultRoute,
  UploadRoute: UploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
